### ISSUE TITLE
HTTP 503 Error on Web UI after Configuration

### ISSUE THREAD

**Issue by fullio2018** [toni-moreno/snmpcollector#538]
I have installed snmpcollector on `Red Hat Enterprise Linux release 8.10 (Ootpa) ` , VM,  and configured it to listen on port 8091. 
````
  "Version": "0.13.1",
  "Commit": "d645bf2",
`````

The process is running and stable. I have verified with `lsof -i :8091 -P -n` that the application is listening on the port. There are no firewalls or SELinux settings blocking the port.

However, when I try to access the Web UI via curl or a browser, I receive an HTTP 503 error.

curl test

`````
[TST][server03].user:~ # curl -v --proxy http://IP:8080 --proxy-user user:psw https://server03:8091/
* Uses proxy env variable no_proxy == '127.0.0.1,localhost'
*   Trying 10.X.X.X...
* TCP_NODELAY set
* Connected to 10.0.0.0 (10.0.0.0) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to server03:8091
* Proxy auth using Basic with user 'mortadelo7'
> CONNECT server03:8091 HTTP/1.1
> Host: server03:8091
> Proxy-Authorization: Basic blablabblablaODA=
> User-Agent: curl/7.61.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 503 Service Unavailable
< Cache-Control: no-cache
< X-XSS-Protection: 1
< Connection: close
< Content-Type: text/html; charset=utf-8
< Content-Length: 1002
< Pragma: no-cache
<
* Received HTTP code 503 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 503 from proxy after CONNECT
[TST][server03].user:~ #

`````

Here is my `/etc/snmpcollector/lan_conf/config.toml` configuration file:

```toml
############################
# General Config
############################

[general]
  instanceID = "LAN - TST"
  datadir = "/etc/snmpcollector/lan_conf/"
  homedir = "/etc/snmpcollector/lan_conf/"
  logdir = "/logs/apps/snmpcollector/lan/"
  logLevel = "info"
  log_mode = "file"

 ############################
 # DataBase Config
 ############################

[database]

  type = "sqlite3"
  name = "snmpcollector_lan"
  log_mode = "none"
  sqllogfile = "sql.log"
  debug = false

############################
# Self Monitorig Config
############################

[selfmon]
  enabled = true
  freq = 60
  prefix = ""
  inheritdevicetags = true
  extratags = [ "instance=lan", "environment=tst" ]

[http]
  #port = 9090
 # adminuser = "lan_user"
 # adminpassword = "password!"


############################
# Embedded WebServer Config
############################

#[http]
  listen   = ":8091"
  protocol = "http"

  adminuser = "lan_user"

  adminpassword = "password!"

  cookieid ="lan"
```

I have checked the snmpcollector logs in `/logs/apps/snmpcollector/lan/` but there are no errors reported.  I am seeking assistance with the configuration to resolve the 503 error.

Here is the output of `netstat` and `lsof`:

```
[TST][server03].user:~ # netstat -tunlp | grep 80
(No info could be read for "-p": geteuid()=48007 but you should be root.)
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      -
tcp6       0      0 :::80                   :::*                    LISTEN      -
tcp6       0      0 :::8086                 :::*                    LISTEN      -
tcp6       0      0 :::8091                 :::*                    LISTEN      -
[TST][server03].user:~ # sudo lsof -nP -iTCP -sTCP:LISTEN
COMMAND      PID    USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
systemd        1    root   63u  IPv4     1832      0t0  TCP *:111 (LISTEN)

snmpcolle  24991    root 4560u  IPv6 57292061      0t0  TCP *:8091 (LISTEN)
alloy     102001    root   12u  IPv4 49702933      0t0  TCP 127.0.0.1:12345 (LISTEN)

[TST][server03].user:~ # sudo lsof -nP -iTCP -sTCP:LISTEN | grep 80
dnsmasq     1942 dnsmasq    5u  IPv4    38081      0t0  TCP *:53 (LISTEN)
dnsmasq     1942 dnsmasq    7u  IPv6    38083      0t0  TCP *:53 (LISTEN)
docker-pr   6604    root    4u  IPv6    90607      0t0  TCP *:8086 (LISTEN)
docker-pr   6750    root    4u  IPv4    86659      0t0  TCP 127.0.0.1:8000 (LISTEN)
docker-pr   7353    root    4u  IPv6    91000      0t0  TCP *:80 (LISTEN)
docker-pr   8012    root    4u  IPv4    91782      0t0  TCP 127.0.0.1:8080 (LISTEN)
snmpcolle  24991    root 4560u  IPv6 57292061      0t0  TCP *:8091 (LISTEN)
[TST][server03].user:~ #
```

LOGGING
snmpcollector.log
`````
time="2025-05-21 17:37:27" level=info msg="Sender thread to : influx_MAIN  already Initialized (skipping Initialization)"
time="2025-05-21 17:37:27" level=info msg="Sender thread to : influx_MAIN  already started (skipping Goroutine creation)"
time="2025-05-21 17:37:27" level=info msg="setting HTML Static Path to /etc/snmpcollector/lan_conf/public"
time="2025-05-21 17:37:27" level=info msg="WEBUI: Server is running on :8091..."
time="2025-05-21 18:02:28" level=info msg="Admin login OK"

`````
http_access.log when i execute curl to  localhost:8091/login
````
[Macaron] 2025-05-21 18:02:28: Started POST /login for 127.0.0.1
[Macaron] 2025-05-21 18:02:28: Completed POST /login 200 OK in 2.607257ms

`````

When i execute curl comands to API endpoints, to http://localhost:8091/   everything works fine, but if i try to access webUI or curls commands from other server, 503 is returned.

Any suggestions?

Thanks!!

Julio Fernández
